### ISSUE TITLE
Is it possible to avoid Environment Variables ?

### ISSUE THREAD

**Issue by irvnriir** [PratyushTripathy/python_gdal_automated_windows#1]
When packaging into end-user products, these are something i don't want to use .

By the way, i looked all over osgeo front-pages for gdal (github, docs, pypi, osgeo4w) and didn't find a way to use it, your setup is the only one that worked, thanks .

**Comment by PratyushTripathy** [comment]
Good to know that it worked for you. Environment variables are necessary, please see [here](https://github.com/PratyushTripathy/python_gdal_automated_windows/tree/main/debugger) as to how to do it manually.
